"""empty message

Revision ID: 4ec3055a6369
Revises: d8c2d9d01613
Create Date: 2022-07-31 21:50:53.756236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec3055a6369'
down_revision = 'd8c2d9d01613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=160), nullable=True),
    sa.Column('height', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.String(length=255), nullable=True),
    sa.Column('blood_pressure', sa.String(length=255), nullable=True),
    sa.Column('blood_sugar', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('patient_record', 'phoneNumber')
    op.drop_column('patient_record', 'patient_name')
    op.drop_column('patient_record', 'patient_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_record', sa.Column('patient_report', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('patient_record', sa.Column('patient_name', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    op.add_column('patient_record', sa.Column('phoneNumber', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('patient_history')
    # ### end Alembic commands ###
