"""empty message

Revision ID: 56aa40abf0cc
Revises: dae1c92cdc79
Create Date: 2022-07-31 23:45:41.880055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56aa40abf0cc'
down_revision = 'dae1c92cdc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'patient_profiles', ['patient_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'patient_profile_id')
    # ### end Alembic commands ###
