"""empty message

Revision ID: 85b37f4d8899
Revises: ae14531368b4
Create Date: 2022-08-03 23:00:36.695661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b37f4d8899'
down_revision = 'ae14531368b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('isPatient', sa.Boolean(), nullable=True))
    op.add_column('patient_profiles', sa.Column('isPatient', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'isPatient')
    op.drop_column('doctor_profiles', 'isPatient')
    # ### end Alembic commands ###
