"""empty message

Revision ID: 9ffe3b11409a
Revises: a1e14c0c4ee2
Create Date: 2022-07-31 15:44:44.724030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffe3b11409a'
down_revision = 'a1e14c0c4ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'doctor_profiles', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
