"""empty message

Revision ID: a1e14c0c4ee2
Revises: 
Create Date: 2022-07-31 11:58:20.192886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e14c0c4ee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=160), nullable=True),
    sa.Column('time', sa.String(length=60), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emailAddress', sa.String(length=160), nullable=True),
    sa.Column('first_name', sa.String(length=160), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phoneNumber', sa.String(length=80), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('doctor', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('specialty', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('phoneNumber', sa.String(length=80), nullable=True),
    sa.Column('emailAddress', sa.String(length=160), nullable=True),
    sa.Column('companyName', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emailAddress')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.Column('emailAddress', sa.String(length=160), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patient_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=160), nullable=True),
    sa.Column('patient_illness', sa.String(length=160), nullable=True),
    sa.Column('patient_report', sa.String(length=255), nullable=True),
    sa.Column('medication', sa.String(length=255), nullable=True),
    sa.Column('phoneNumber', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_record')
    op.drop_table('patient_profiles')
    op.drop_table('doctor_profiles')
    op.drop_table('appointments')
    op.drop_table('appointment_schedule')
    # ### end Alembic commands ###
