"""empty message

Revision ID: ae14531368b4
Revises: ba79bfc22bc9
Create Date: 2022-08-02 21:17:21.095212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae14531368b4'
down_revision = 'ba79bfc22bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_history', sa.Column('visitation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_history', 'visitation_date')
    # ### end Alembic commands ###
