"""empty message

Revision ID: ba79bfc22bc9
Revises: 39e96cf5b9ea
Create Date: 2022-08-02 01:20:10.313986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba79bfc22bc9'
down_revision = '39e96cf5b9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_diagnosis', sa.Column('filenames', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_diagnosis', 'filenames')
    # ### end Alembic commands ###
