"""empty message

Revision ID: d8c2d9d01613
Revises: 9ffe3b11409a
Create Date: 2022-07-31 21:09:38.791603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c2d9d01613'
down_revision = '9ffe3b11409a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'booked')
    # ### end Alembic commands ###
